apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: boa-waypoint
  annotations:
    istio.io/for-service-account: bank-of-anthos
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: ALL
